---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: graphite_pre.yml
- include_tasks: graphite_install.yml

- block: # Config Graphite
  - include_tasks: graphite_search_config.yml
  - include_tasks: graphite_post.yml
  tags:
    - graphite-config
